In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.compat.v1.enable_eager_execution()

In [6]:
print(tf.add(1,2))
print(tf.add([1,2], [3,4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.io.encode_base64("hello world"))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)


In [7]:
print(tf.square(2) + tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [8]:
x = tf.matmul([[1]], [[2, 3]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


In [9]:
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [12]:
ndarray = np.ones([3, 3])
tensor = tf.multiply(ndarray, 42)
print(tensor)
print(np.add(tensor, 1))
print(tensor.numpy())

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]
