In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.compat.v1.enable_eager_execution()

In [3]:
print(tf.add(1,2))
print(tf.add([1,2], [3,4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.io.encode_base64("hello world"))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)


In [4]:
print(tf.square(2) + tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [5]:
x = tf.matmul([[1]], [[2, 3]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


In [6]:
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [7]:
ndarray = np.ones([3, 3])
tensor = tf.multiply(ndarray, 42)
print(tensor)
print(np.add(tensor, 1))
print(tensor.numpy())

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [13]:
# x = tf.random_uniform_initializer([3,3])
x = tf.compat.v1.random_uniform([3, 3])

In [9]:
print("Is there a GPU available: ", tf.test.is_gpu_available())

Is there a GPU available:  True


In [14]:
print("Is the Tensor on GPU #0:  ", x.device.endswith("GPU:0"))

Is the Tensor on GPU #0:   True


In [15]:
import time

In [17]:
def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)
    result = time.time() - start
    print("10 loops :{:0.2f}ms".format(1000*result))

In [18]:
print("on cpu:")
with tf.device("CPU:0"):
    x = tf.compat.v1.random_uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)
    
print("on gpu:")
with tf.device("GPU:0"):
    x = tf.compat.v1.random_uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

on cpu:
10 loops :88.76ms
on gpu:
10 loops :407.91ms


In [19]:
ds_tensor = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

In [20]:
import tempfile

In [21]:
_, filename = tempfile.mkstemp()

In [22]:
filename

'C:\\Users\\rising\\AppData\\Local\\Temp\\tmpjverv14j'

In [24]:
with open(filename, "w") as f:
    f.write("""Line 1
Line 2
Line 3
  """)
ds_file = tf.data.TextLineDataset(filename)

In [ ]:
d